### ISSUE TITLE
Cannot decode signatures on VEVO videos (possibly others)

### ISSUE THREAD

**Issue by dwmc15873** [xaicron/p5-www-youtube-download#19]
I am unable to download videos from VEVO on youtube. Every time I try I get output like the following:

$ youtube-download http://www.youtube.com/watch?v=4m1EFMoRFvY
Unable to decode signature E3C73C7F45F331F5392680E32BD9F6AC64D10970C868.FCE3D72643F38323CE1C042E98491E8A4378FBE3BE99 of length 89 at /usr/local/bin/youtube-download line 51

Every non-vevo video I have tried today works, but vevo videos don't. It appears that youtube is doing something special for those videos.

**Comment by oalders** [comment]
New release is on its way to CPAN.  Please ping back here if the problem has not been solved.
