### ISSUE TITLE
403 forbidden

### ISSUE THREAD

**Issue by BrandonChubb** [xaicron/p5-www-youtube-download#24]
Some videos, for example kDMsVApzv9w, return 403 Forbidden.  I don't know enough yet to know if this is some specific encoding that causes this?  (Not sure how to know what encoding it see look at the we page.)

Excellent tool!  Thanks for all your work!

**Comment by oalders** [comment]
A new release is on its way to CPAN.  Please post an update here as to whether its still an issue for you.

**Comment by BrandonChubb** [comment]
Fixed!  Awesome. :)

**Comment by oalders** [comment]
Great to hear. Thanks for letting us know.  :)
