### ISSUE TITLE
garbage after JSON object

### ISSUE THREAD

**Issue by java4fun** [xaicron/p5-www-youtube-download#27]
I run eg/cb.pl, getting the following error. I use cygwin/perl-5.14

garbage after JSON object, at character offset 15409 (before ";(function() {var en...") at F:/p5-www-youtube-download/p5-www-youtube-download/lib/WWW/YouTube/Download.pm line 229.

**Comment by profplump** [comment]
FYI: I've moved to this: http://rg3.github.io/youtube-dl/

It's not a handy perl module, but it's easy to use to download videos and/or extract information from YT, and it's being maintained.

**Comment by oalders** [comment]
This was closed by #31 and a new release is on its way to CPAN.
