### ISSUE TITLE
Cann't download youtube video

### ISSUE THREAD

**Issue by ovntatar** [xaicron/p5-www-youtube-download#30]
Hi I try to download some data from youtube unfortunately I get follow errror message if run youtube-download script:

Video
https://www.youtube.com/watch?v=G5TnlcNCcBQ

Message
garbage after JSON object, at character offset 12455 (before ";(function() {var en...") at /usr/local/share/perl/5.14.2/WWW/YouTube/Download.pm line 226.

Perl Version
This is perl 5, version 14, subversion 2 (v5.14.2) built for x86_64-linux-gnu-thread-multi
(with 88 registered patches, see perl -V for more detail)

**Comment by oalders** [comment]
This was closed by #31 and a new release is on its way to CPAN. Thanks for reporting!
