### ISSUE TITLE
deb package repo

### ISSUE THREAD

**Issue by subogero** [xaicron/p5-www-youtube-download#33]
I installed the library from Debian Wheezy, but encountered "garbage after JSON object" errors. What's the state of Debian packaging of this project? Any chance to get fixed versions into Wheezy? If not, is there a deb package repo or PPA available?

Do you create deb files from new releases? If so, I can actually offer to host it in my own package repo

```
deb http://linux.subogero.com/deb/ /
```

Background: I'm writing a FAST cmdline YouTube search/playback/download/URL-extract utility to replace the extremely slow Python based youtube-dl. It's nearly finished, but I just realized your library exists.

**Comment by oalders** [comment]
I actually don't know who does the Debian package for this project, but if the re-package based on the latest version, this issue should be resolved.

**Comment by subogero** [comment]
Let's hope for the best and wait for our kind deb-packager to turn up. :-)

**Comment by oalders** [comment]
Based on #42 I'd say that is still actively being packaged by Debian.  :)
