### ISSUE TITLE
Undeclared dependency Module::Build::Tiny in 0.61

### ISSUE THREAD

**Issue by perlpunk** [xaicron/p5-www-youtube-download#53]
When I execute `perl Build.PL`, I get
`Can't locate Module/Build/Tiny.pm in @INC`

I stumbled over this when maintaining the automatic perl module updates for openSUSE.

**Comment by oalders** [comment]
Thanks for reporting @perlpunk.  I had switched to `Dist::Zilla` and completely ignored the `Build.PL` that was not being updated.
