### ISSUE TITLE
failed to find video urls 

### ISSUE THREAD

**Issue by gmuc** [xaicron/p5-www-youtube-download#55]
I got the error:

$ youtube-download https://www.youtube.com/watch?v=YUVVuX-mTUI
failed to find video urls at /usr/local/bin/youtube-download line 64

$ youtube-download -V
youtube-download (WWW::YouTube::Download) version 0.62

OSX 10.14.6

$ perl -v

This is perl 5, version 18, subversion 4 (v5.18.4) built for darwin-thread-multi-2level

I tried different youtube URLs, every time the same problem :(

**Comment by DavidEGx** [comment]
Same problem here.

$ youtube-download -V
youtube-download (WWW::YouTube::Download) version 0.60

$ perl -v
This is perl 5, version 28, subversion 1 (v5.28.1) built for x86_64-linux-gnu-thread-multi
(with 61 registered patches, see perl -V for more detail)

**Comment by oalders** [comment]
Thanks for reporting.  I'm happy to accept a PR to fix any errors.

**Comment by sdondley** [comment]
Ditto. Using v. 0.62 of the module.

```
This is perl 5, version 24, subversion 4 (v5.24.4) built for darwin-2level
```

This module used to work without issue. I'm on OS X Catalina, 10.15.3.

**Comment by sdondley** [comment]
AS best I can tell, the $args hash returned by $self->_get_args($content) call do not contain the {fmt_list} and {url_encoded_fmt_stream_map} properties.

**Comment by kiwiroy** [comment]
I've managed to download a few videos with the 8e59d94 applied. Tests fail, but that appears to be a `xt` pod coverage thing. There's an array of `adaptiveFormats` in the JSON that are ignored and the format tag is now raw `mimeType` in the `-a` option.

**Comment by oalders** [comment]
Do you want to create a pull request?
