### ISSUE TITLE
Can't upload a new release

### ISSUE THREAD

**Issue by oalders** [xaicron/p5-www-youtube-download#59]
@xaicron I'm unable to upload any new, official releases:

```
$ grep WWW::YouTube::Download /home/metacpan/CPAN/modules/06perms.txt
WWW::YouTube::Download,XAICRON,f
```

My PAUSE id `OALDERS` is no longer listed for this module in the PAUSE permissions.

**Comment by xaicron** [comment]
@oalders I'm sorry I was missing this issue.

I added the PAUSE permissions. Please check it.
And, if no problems that will change primary permissions.

Thank you for your maintenance.

**Comment by oalders** [comment]
@xaicron thank you so much! I see my perms have been restored now.  I really appreciate it. :)
